# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

# This line is required to be able to install Tapdaq SDK and network adapters
source 'https://github.com/tapdaq/cocoapods-specs.git'

target 'RNTapdaq' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNTapdaq
  pod "Tapdaq", "7.4.0"
  pod 'Tapdaq/AppLovin'

end
